### ISSUE TITLE
Issue 001 - Add Analysis static code tool  - Next week

### ISSUE THREAD

**Issue by miguelpimentel** [carolquiterio/simple-kotlin-projects#1]
**Issue**: 001

**Description**

Add lint library to your android project

** What is **

It is a tool that help analyze your code. Finding issues or bad patterns for implementations 

**Recomendations**

* https://www.youtube.com/watch?v=b-AWsOmszWk
* https://proandroiddev.com/detecting-kotlin-code-smells-with-detekt-e79c52a35faf 
* https://medium.com/android-dev-br/introdução-detekt-7f5eefcd6d9c

**Comment by carolquiterio** [comment]
Done.
